
name: CI-CD Pipeline
# Trigger pipeline on push request to main branch
on:
  push:
    branches: [ "main" ]

jobs:
  # Step1: Compile job
  compile:
    name: compile java project
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo
    - uses: actions/checkout@v4
    # set Up java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    # compile the project
    - name: Compile
      run: mvn compile
